[package]
name = "bvh"
version = "0.1.0"
edition = "2021"

[dependencies]
valence = { workspace = true }
utils = { workspace = true }
bevy_time = { workspace = true }
vek = "0.17.1"
arrayvec = "0.7.6"
rayon = "1.10.0"
ordered-float = "4.6.0"